#!/bin/bash
#set -x
unset DEBIAN_FRONTEND

if ls -- /var/www/* >/dev/null 2>&1
then 
	if su -s /bin/bash www-data -c 'ls /var/www/*' >/dev/null 2>&1
	then 
		echo "Welcome to the COMP[29]041 Docker webserver container"
	else
		echo "/var/www is not readable to the web-server (user www-data), making it readable"
		echo "ls -ld /var/www"
		ls -ld /var/www 
		echo "chgrp www-data /var/www /var/www/*.cgi"
		chgrp www-data /var/www /var/www/*.cgi /var/www/*.html
		echo "chmod g+rx /var/www /var/www/*.cgi /var/www/*.html"
		chmod g+rx /var/www /var/www/*.cgi /var/www/*.html
		echo "ls -ld /var/www "
		ls -ld /var/www 
	fi
else
	echo "No files in /var/www"
	echo "You need to mount a directory on /var/www for example:"
	echo "docker run -v c:/users/andrewt/cgi:/var/www comp2041/webserver"
	exit
fi


if test $# = 0
then
	/usr/sbin/apache2ctl -D FOREGROUND
else
	"$@"
fi